# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Midnight
url:                 https://github.com/midnight2104
baseurl:             https://midnight2104.github.io
paginate:            3

# About/contact
author:
  name:              midnight2104
  url:               https://github.com/midnight2104
  email:             midnight2104@foxmail.com


