# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Midnight
description:         'There is a Crack in Everything, that's How the Light Gets in 。'
url:                 https://github.com/midnight2104
baseurl:             https://midnight2104.github.io
paginate:            5

# About/contact
author:
  name:              midnight2104
  url:               https://github.com/midnight2104
  email:             ll2104@163.com


